-- AlterTable
ALTER TABLE `Driver` ADD COLUMN `class` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `defensive` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `dob` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `medical` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `nationalID` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `phone` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `year` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `Vehicle` ADD COLUMN `colour` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `netWeight` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `weight` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `year` VARCHAR(191) NOT NULL DEFAULT '';
